### ISSUE TITLE
Typo in installation section of README

### ISSUE THREAD

**Issue by pwhelan161** [Tivix/django-braintree#1]
For the "Add these lines in settings.py file:" section it should say:

from braintree import Configuration, Environment
Configuration.configure(
    Environment.Sandbox,
    BRAINTREE_MERCHANT,
    BRAINTREE_PUBLIC_KEY,
    BRAINTREE_PRIVATE_KEY,
 )

**Comment by dfryta** [comment]
Thanks again! Already fixed.
