### ISSUE TITLE
How do I get pay?

### ISSUE THREAD

**Issue by bluekite2000** [Tivix/django-braintree#2]
I see you have pay.html
but you dont have pay in urls.py or views.py???
After user enters his credit card number, how do I charge him?

**Comment by chachra** [comment]
Hi,

The pay() functionality is all well coded in braintree's python API. The point of this app. is to make capturing, securely storing (via vault) the Credit Card data etc.

See https://github.com/braintree/braintree_python/blob/master/braintree/transaction.py for details on how to charge the user.

Hope this helps.

Cheers,
Sumit
