### ISSUE TITLE
Clarify in readme the correct package on pypi

### ISSUE THREAD

**Issue by pg1671** [Tivix/django-braintree#4]
There is more than one django-braintree on pypi and the readme would suggest to try to  install this via pip etc which will install a different package.  The correct package is tivix-django-braintree.  

Might cause some confusion to first time users when they have installed a completely different package.

Thanks.

**Comment by tammyalexandra** [comment]
+1

**Comment by chachra** [comment]
Added pip install tivix-django-braintree in README. Thanks!
