### ISSUE TITLE
Django 1.5 updates

### ISSUE THREAD

**Issue by adrienbrunet** [Tivix/django-braintree#6]
For django compatibilities (?)

**\* django-braintree/django_braintree/templates/django_braintree/fragments/pay.html 

line 7:
href="{% url payments_billing %}" 
should be changed to 
href="{% url 'payments_billing' %}"

**\* django-braintree/django_braintree/templates/django_braintree/fragments/pay.html 
line 28:
 window.location = '{% if cc_form_success_redirect_url %}{{ cc_form_success_redirect_url }}{% else %}{% url "payments_billing" %}{% endif %}';
should be changed to
window.location = "{% if cc_form_success_redirect_url %}{{ cc_form_success_redirect_url }}{% else %}{% url 'payments_billing' %}{% endif %}";

as well as 

line 13:
{% url payments_billing %}
which should be changed to
{% url 'payments_billing' %}

**Comment by mateusz-sikora** [comment]
Fixed.
https://github.com/Tivix/django-braintree/commit/7beb2c8392c2a454c36b353818f3e1db20511ef9
