### ISSUE TITLE
Support beyond 1.4

### ISSUE THREAD

**Issue by askpatrickw** [Tivix/django-braintree#9]
Is this an abandoned project?

There are many incompatibilities with releases post 1.4.

**Comment by chachra** [comment]
Am sure... yes we don't currently develop it. I'm happy to review/merge any PR's or make you a committer on the project if you'd like or have done similar previous work you can share. Thanks @W7PEA

**Comment by askpatrickw** [comment]
@MrYoda has a fork with what looks like a lot of the changes we'd need. Maybe @MrYoda will send a PR.

**Comment by MrYoda** [comment]
HI there! My PR with my pretty commits is already here https://github.com/Tivix/django-braintree/pull/8, but I'm not maintainer of this project.
My commits was many many monthes ago, and I think the whole project is a little bit obsolete now.

**Comment by velis74** [comment]
It seems [thinkin3d](https://github.com/thinkin3d/django-braintree) has the most up-to-date fork?
